# Site
copyright: "EXXETA AG"
name: "EXXETA data science and machine learning blog"
description: "Industry-grade data science and machine learning from Berlin."
meta_description: "Articles on the application of artificial intelligence in various industries."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
permalink: /:year/:month/:title
google_analytics: ''
disqus: ''
mailchimp-list: ''

# Authors
authors:
  weisseo:
    name: Oliver Weisse
    display_name: Oliver Weisse
    gravatar: fedcd61ed407622bccba9e6d5dd06889
    email: oliver.weisse@exxeta.com
    phone: +49 173 748 00 98
    web: https://www.linkedin.com/in/oliver-weisse-0b3916109/
    twitter:
    description: >
                  Oliver holds degrees in physics from HU Berlin with research experience at Uppsala University
                  and Potsdam Institute for Climate Impact Research.
                  He is an experienced data science and machine learning consultant.
  waltherg:
    name: Dr. Georg Walther
    display_name: Dr. Georg Walther
    gravatar: 7eb7232a7c473ae8edf6e3b40c6b74a7
    email: georg.walther@exxeta.com
    phone: +49 152 2269 0102
    web: https://www.linkedin.com/in/georgwalther/
    twitter:
    description: >
                  Georg holds degrees in biochemistry and computational biology from ETH Zurich,
                  completed research at UBC Vancouver and holds a PhD degree from John Innes Centre.
                  He has vast industry experience in the application of data science and machine learning methodologies.

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
